Updating visuals
bde-isima/bde.isima.fr pull request #21
Opened 2022-02-22 09:31 UTC by citorva

Replacing visual with up-to-date images and making it readable in a dark theme.

## Footer
### Light theme
![image](https://user-images.githubusercontent.com/16229435/155102555-25aebd39-31b5-4beb-83fd-db683e6a4219.png)
### Dark theme
![image](https://user-images.githubusercontent.com/16229435/155102437-d626f007-7aeb-4cdd-99cc-c3632f50da89.png)

## 404 Error
### Light theme
![image](https://user-images.githubusercontent.com/16229435/155103059-4f8b7ce6-c16e-493b-9279-c306dc30b536.png)
### Dark theme
![image](https://user-images.githubusercontent.com/16229435/155103370-99207fe2-07b1-4e8c-9668-739412bce187.png)

2022-02-22 10:05 UTC, IraSkyx requested changes

2022-02-22 10:06 UTC, IraSkyx commented
Nice, ça rend globalement bien mieux surtout en dark mode

2022-02-22 10:13 UTC, citorva commented on app/pages/404.tsx
> +          Il se trouve que tu te soit perdu
Ok

2022-02-22 11:09 UTC, citorva commented
Normalement, c’est bon

2022-02-22 17:07 UTC, citorva reviewed
All changes has been made

2022-02-22 20:05 UTC, IraSkyx approved these changes

2022-02-22 20:16 UTC, merged

2022-02-26 10:31 UTC, citorva commented
Le logo de l’isima n’est pas propre étant donné que j’ai du le récupérer depuis une image matricielle. Je vais essayer de récuperer une version verctorielle propre