Implement listeux fonctionnality
bde-isima/bde.isima.fr pull request #45
Opened 2023-09-14 11:51 UTC by Topin2001

2023-09-15 08:56 UTC, citorva requested changes
Quelques petites améliorations à faire, courage

2023-09-15 08:56 UTC, citorva commented on app/entities/auth/mutations/login.ts
> +      }
utiliser l'opérateur ternaire pour garder le const

2023-09-15 08:56 UTC, citorva commented on app/entities/auth/mutations/login.ts
> +          })*/
ça va être compliqué de se connecter sans mail 🤔

2023-09-15 08:56 UTC, citorva commented on public/static/images/illustrations/Dashboard.webp
Remplacer par une image vectorielle mieux intégrée, je pourrais m'en charger

2023-09-15 09:08 UTC, citorva commented on app/components/dashboard/cashing/catalog/Article.tsx
> +          <Image src={loadImageSrc()} width={size} height={size} alt={`Photo ${article?.name}`} />
J'ai également pensé de mettre cette image dans les ressources du site afin d'éviter de dépendre d'un service externe pour les ressources statiques

2023-09-25 12:52 UTC, Topin2001 commented on public/static/images/illustrations/Dashboard.webp
Je te laisse le faire du coup

2023-09-25 20:28 UTC, citorva reviewed
Courage, encore quelques modifications et c'est fini 😊

2023-09-25 20:28 UTC, citorva commented on app/components/dashboard/cashing/catalog/Article.tsx
Ok, je ne voyais pas ça comme ça 🤔

2023-09-25 20:28 UTC, citorva commented on app/core/utils/isListeux.ts
Peut être simplifié

2023-09-25 20:28 UTC, citorva commented on app/entities/auth/mutations/login.ts
> +    ? user.roles.includes('listeux') && !user.roles.includes('bde') && !user.roles.includes('*')
n'existe-t-il pas une fonction pour cette condition déjà? 🤔

2023-10-04 20:31 UTC, merged