Enable status display
bde-isima/bde.isima.fr pull request #54
Opened 2024-02-08 12:46 UTC by Topin2001

Added a status (member/non-member) to the cashing dialog

2024-04-29 14:51 UTC, Topin2001 commented
@citorva can you check this please ?

2024-05-16 11:28 UTC, citorva requested changes
Ça me paraît ok, cependant, il y a un changemnt dans SearchUser.tsx ligne 43 qui semble du à un outil automatique. Je te conseille de le supprimer

2024-05-16 11:28 UTC, citorva commented
D'ailleurs, désolé du retard :sweat_smile:

2024-05-23 09:30 UTC, citorva approved these changes

2024-05-23 09:34 UTC, merged